import React from 'react'
import styles from './Profile.module.sass'
import PropTypes from 'prop-types';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`simple-tabpanel-${index}`}
      aria-labelledby={`simple-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 3 }}>
          <Typography>{children}</Typography>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function a11yProps(index) {
  return {
    id: `simple-tab-${index}`,
    'aria-controls': `simple-tabpanel-${index}`,
  };
}

const Profile = () => {

    const [value, setValue] = React.useState(0);

    const handleChange = (event, newValue) => {
    setValue(newValue);
    };

  return (
    <>
        <div className={styles.eightyPercentWrapper}>
            <div className={styles.profileContainer}>
                <div className={styles.bioDataWrapper}>
                    <div className={styles.coverImageWrapper}>
                        {/* <img src="./ozean_Images/Images/profileBg.png" alt="profileBgimg" /> */}
                    </div>
                    <div className={styles.profileImageWrapper}>
                        <img src="./ozean_Images/Images/profileImg.png" alt="profileimg" />
                    </div>
                    <div className={styles.bioDataInfoWrapper}>
                        <Typography className={styles.nameText}>anmutigstudio</Typography>
                        <Typography className={styles.discriptionText}>Anmutig Studio was launched as a collection of unique NFTs generated by algorithm on the ETH blockchain in oct 2021.</Typography>
                    </div>
                </div>
                <div className={styles.nftsByCategoriesWrapper}>
                <Box sx={{ width: '100%' }}>
                    <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                        <Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
                        <Tab label="Item One" {...a11yProps(0)} />
                        <Tab label="Item Two" {...a11yProps(1)} />
                        <Tab label="Item Three" {...a11yProps(2)} />
                        </Tabs>
                    </Box>
                    <TabPanel value={value} index={0}>
                        Item One
                    </TabPanel>
                    <TabPanel value={value} index={1}>
                        Item Two
                    </TabPanel>
                    <TabPanel value={value} index={2}>
                        Item Three
                    </TabPanel>
                    </Box>
                </div>
            </div>
        </div>
    </>
  )
}

export default Profile